#!/usr/bin/env bash
# Providers -> repository, the mirror of scripts/install.sh. For capturing what
# a tool wrote on its own — skill-creator writes new skills straight into the
# directory it scans — not for hand edits: those belong in prompts/, which is
# the source of truth.
#
#   ./prompts/capture.sh                 every provider
#   ./prompts/capture.sh claude-code     just this one
#   ./prompts/capture.sh --force         discard whatever prompts/ holds

PROMPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$PROMPTS_DIR/providers.sh"

capture_provider() {
    local provider="$1" entry kind src dest

    if [ -z "${PROVIDERS[$provider]+x}" ]; then
        echo "✗ $provider: not a known provider"
        FAILED=1
        return
    fi

    while IFS= read -r entry; do
        kind="${entry%%:*}"
        src="${entry#*:}"
        dest="$PROMPTS_DIR/$kind"

        if [ -n "${ADAPTERS[$provider:$kind]-}" ]; then
            echo "· $provider ($kind): generated by the install, nothing to capture"
            continue
        fi

        if [ ! -d "$src" ]; then
            echo "✗ $provider: $src does not exist"
            FAILED=1
            continue
        fi

        [ "$FORCE" = 1 ] \
            || guard "$provider ($kind)" "$src" "$dest" "Deploying them first: ./scripts/install.sh" \
            || { FAILED=1; continue; }

        mkdir -p "$dest"
        rsync -a --delete "$src/" "$dest/"
        echo "✓ $provider: $kind <- $src"
    done < <(provider_entries "$provider")
}

FORCE=0
FAILED=0
args=()
for a in "$@"; do
    [ "$a" == "--force" ] && FORCE=1 || args+=("$a")
done

[ ${#args[@]} -gt 0 ] || args=("${!PROVIDERS[@]}")
for provider in "${args[@]}"; do
    capture_provider "$provider"
done

exit $FAILED
