#!/usr/bin/env bash

DESKTOP_APT_PACKAGES=(
    alacritty
    blueman
    bluez
    brightnessctl
    file-roller
    i3-wm
    i3status
    imagemagick
    gir1.2-gtk-3.0
    libnotify-bin
    network-manager
    network-manager-gnome
    nautilus
    papirus-icon-theme
    pavucontrol
    pipewire-audio
    playerctl
    python3-gi
    rofi
    thunar
    thunar-archive-plugin
    wireplumber
    xfce4-notifyd
    xfce4-panel
    xfce4-power-manager
    xfce4-screenshooter
    xfce4-session
    xfce4-settings
    xdg-utils
    xfdesktop
)
