#!/usr/bin/env python3
"""Generates the greeter's wireframe terrain, as one still on a transparent
ground.

    python3 greeter.py && rsvg-convert -w 2560 -h 1440 greeter.svg -o greeter.png

The mesh is emitted rather than drawn, because a ridgeline authored by hand
reads as a vector illustration and a summed-noise heightmap reads as terrain.
The SVG is this script's output and not a source file; edit here.

Transparent, and the mesh alone: the greeter lays its own surface and hatch
underneath, then either animates this terrain on the GPU or falls back to this
still. Both have to stack the same way, so neither carries the ground with it.
"""

import random

W, H = 2560, 1440

# Grid resolution. Rows run across the view, columns run away from the camera.
COLS, ROWS = 170, 70

# Camera. Distances are in terrain units, the focal length in pixels.
FOCAL = 1150.0
EYE_HEIGHT = 1.05
Z_NEAR, Z_FAR = 1.45, 15.0

# Where the horizon sits. The terrain has to leave the upper third alone: the
# clock lives there, and a mesh behind it would fight the one thing on this
# screen anybody actually reads.
HORIZON = H * 0.40

# Half-width of the terrain in its own units, at the near edge. Wide enough that
# the near rows run off both sides instead of ending in mid-air.
HALF_WIDTH = 2.35

RELIEF = 1.55
SEED = 20260915


def value_noise(seed, lattice):
    """One octave: random values on a coarse lattice, smoothstepped between."""
    rng = random.Random(seed)
    # Two spare rows and columns, not one: u and v reach 1.0 exactly at the far
    # edge of the grid, where the cell lookup still asks for i + 1.
    grid = [[rng.random() for _ in range(lattice + 2)] for _ in range(lattice + 2)]

    def sample(u, v):
        x, y = u * lattice, v * lattice
        i, j = int(x), int(y)
        fx, fy = x - i, y - j
        # Smoothstep, not linear: a linear blend leaves the lattice visible as
        # creases along every cell boundary, which on a wireframe reads as a
        # grid artefact rather than as terrain.
        fx = fx * fx * (3 - 2 * fx)
        fy = fy * fy * (3 - 2 * fy)
        a = grid[j][i] * (1 - fx) + grid[j][i + 1] * fx
        b = grid[j + 1][i] * (1 - fx) + grid[j + 1][i + 1] * fx
        return a * (1 - fy) + b * fy

    return sample


OCTAVES = [(value_noise(SEED + n, 2 ** (n + 1)), 0.5 ** n) for n in range(6)]
NORM = sum(weight for _, weight in OCTAVES)


def height(u, v):
    h = sum(octave(u, v) * weight for octave, weight in OCTAVES) / NORM
    # Ridged: folding the noise about its midpoint turns rounded hills into
    # crests, which is what the reference's silhouette actually is.
    h = 1.0 - abs(h - 0.5) * 2.0
    return (h ** 2.2) * RELIEF


def project(u, v):
    """Grid coordinates in [0,1] to screen pixels."""
    z = Z_NEAR * (1 - v) + Z_FAR * v
    scale = FOCAL / z
    x = W / 2 + (u * 2 - 1) * HALF_WIDTH * scale
    y = HORIZON + (EYE_HEIGHT - height(u, v)) * scale
    return x, y


def fade(v):
    """Stroke opacity by depth: the far rows dissolve into the ground.

    The ceiling is low on purpose. This is the material a plate sits on, and a
    mesh bright enough to be read before the plate is a subject, not a ground.
    """
    near = 1.0 - v
    return round(0.025 + 0.30 * (near ** 1.7), 4)


def polyline(points, opacity):
    coords = " ".join(f"{x:.1f},{y:.1f}" for x, y in points)
    return f'<polyline points="{coords}" stroke-opacity="{opacity}"/>'


def main():
    lines = []

    # Rows first, then columns: a mesh needs both, and drawing all of one
    # direction before the other keeps the opacity runs contiguous.
    for j in range(ROWS):
        v = j / (ROWS - 1)
        pts = [project(i / (COLS - 1), v) for i in range(COLS)]
        lines.append(polyline(pts, fade(v)))

    for i in range(COLS):
        u = i / (COLS - 1)
        pts = [project(u, j / (ROWS - 1)) for j in range(ROWS)]
        # A column spans every depth, so it takes the mean of what its ends
        # would get rather than one end's value.
        lines.append(polyline(pts, round((fade(0.0) + fade(1.0)) / 2, 4)))

    mesh = "\n    ".join(lines)

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">
<!-- Generated by greeter.py; edit there, not here. -->
  <defs>
    <!-- The vignette. Elliptical rather than circular: the frame is 16:9 and a
         circular falloff leaves the left and right thirds lit while the top and
         bottom are already black. -->
    <radialGradient id="vignette" cx="0.5" cy="0.62" r="0.52">
      <stop offset="0.00" stop-color="#FFFFFF"/>
      <stop offset="0.38" stop-color="#B4B4B4"/>
      <stop offset="1.00" stop-color="#000000"/>
    </radialGradient>
    <mask id="mVignette">
      <rect width="{W}" height="{H}" fill="url(#vignette)"/>
    </mask>

  </defs>

  <g mask="url(#mVignette)" fill="none" stroke="#E8EDF1" stroke-width="1"
     stroke-linecap="round" stroke-linejoin="round">
    {mesh}
  </g>
</svg>
"""
    with open("greeter.svg", "w") as f:
        f.write(svg)


if __name__ == "__main__":
    main()
