source = ~/.config/theme/endfield.conf

$font = "HarmonyOS Sans"

general {
    grace = 1
    fractional_scaling = 2
    immediate_render = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

# INPUT FIELD
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0) # no fill
    dots_spacing = 0.3
    rounding = 0

    font_color = rgb($textSecondary)
    outer_color = $lockAccent
    check_color = rgb($accentSoft)
    fail_color = rgb($danger)
    capslock_color = rgb($accent)

    fade_on_empty = false
    font_family = $font
    hide_input = false

    position = 0, -50
    halign = center
    valign = center
}

# HOURS
label {
    monitor =
    text = cmd[update:1000] date +"%-I:%M %p"
    color = rgb($textPrimary)
    font_size = 100
    font_family = $font
    position = 0, 100
    halign = center
    valign = center
}

# KEYBOARD LAYOUT
label {
    monitor =
    text = $LAYOUT
    color = rgb($textMuted)
    font_size = 12
    font_family = $font
    position = 0, -100
    halign = center
    valign = center
}
