exec-once = uwsm app -- waybar
exec-once = uwsm app -- hyprpaper --config /home/nyxze/.config/hypr/hyprpaper.conf
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- qs -c endfield
exec = $HOME/.config/hypr/scripts/displays.py apply
exec-once = $HOME/.config/hypr/scripts/displays.py watch
