# Endfield theme for btop.

theme[main_bg]="#171717"
theme[main_fg]="#dfe3e3"
theme[title]="#dfe3e3"
theme[hi_fg]="#fffa00"
theme[selected_bg]="#313739"
theme[selected_fg]="#fffa00"
theme[inactive_fg]="#7e807c"
theme[graph_text]="#a0aaa9"
theme[meter_bg]="#313739"
theme[proc_misc]="#657136"

theme[cpu_box]="#313739"
theme[mem_box]="#313739"
theme[net_box]="#313739"
theme[proc_box]="#313739"
theme[div_line]="#565656"

theme[temp_start]="#657136"
theme[temp_mid]="#f8f546"
theme[temp_end]="#e95460"

theme[cpu_start]="#657136"
theme[cpu_mid]="#a3b84a"
theme[cpu_end]="#fffa00"

theme[free_start]="#565656"
theme[free_mid]="#7e807c"
theme[free_end]="#a0aaa9"

theme[cached_start]="#657136"
theme[cached_mid]="#a3b84a"
theme[cached_end]="#f8f546"

theme[available_start]="#7e807c"
theme[available_mid]="#a0aaa9"
theme[available_end]="#dfe3e3"

theme[used_start]="#a3b84a"
theme[used_mid]="#f8f546"
theme[used_end]="#e95460"

theme[download_start]="#657136"
theme[download_mid]="#a3b84a"
theme[download_end]="#f8f546"

theme[upload_start]="#565656"
theme[upload_mid]="#a0aaa9"
theme[upload_end]="#fffa00"

theme[process_start]="#657136"
theme[process_mid]="#f8f546"
theme[process_end]="#fffa00"
