preload = /home/nyxze/.config/theme/greeter.png
ipc = on
splash = false

wallpaper {
	monitor = HDMI-A-1
	path = /home/nyxze/.config/theme/greeter.png
	fit_mode = cover
}

wallpaper {
	monitor = eDP-1
	path = /home/nyxze/.config/theme/greeter.png
	fit_mode = cover
}
